meta-refkit/conf/distro/include/refkit-passwd
meta-refkit/recipes-image/images/refkit-image-gateway.bb

Pull in the latest changes from meta-iot-web. Also, re-name restful user home directory. 
Signed-off-by: Sudarsana Nagineni sudarsana.nagineni@intel.com

Pull in the latest changes from meta-iot-web

---

meta-refkit/conf/distro/include/refkit-supported-recipes.txt

* openembedded-core e02716c...d110937 (79):
> nss: Fix nss-native so the checksum doesn't change with BUILD_ARCH
> sstate: Make absolute symlinks an error
> openssl/fontconfig/bzip2: Use relative symlinks instead of absolute ones (using a new class)
> lib/oe/path: Add replace_absolute_symlinks function
> gcc-cross-initial: Remove unneeded temporary sysroot
> python3-native: Remove tests to save copying uneeded files around
> glibc-package: Avoid race sstate races with do_stash_locale
> oeqa/selftest/pkgdata: use m4 instead of bash
> dosfstools: upgrade to 4.1
> image_types.bbclass: fix image dependency chain collection
> kernel-module-split: Allow custom suffix for package names
> iproute2: Inherit pkgconfig
> pcmciautils: Inherit pkgconfig
> qemu: Add missing 'inherit pkgconfig'
> …

intel-iot-refkit: manually pull in updates

---

meta-iotqa/lib/oeqa/runtime/sanity/baseos.py

meta-iotqa: Dump whole journal when boot error test fails

---

meta-iotqa/conf/test/refkit-image-gateway.manifest

meta-iotqa: Enable nodejs test for gateway profile

---

meta-refkit/conf/distro/refkit.conf
meta-refkit/recipes-multimedia/pulseaudio/pulseaudio_%.bbappend

* openembedded-core d110937...9f225ef (93):
* bitbake 95deeca...b977737 (6):
* meta-intel e8fd58c...5153dad (10):
* meta-security-isafw f44f15b...35ca3b1 (1):

intel-iot-refkit: manual submodule update

---

meta-iotqa/README.md

meta-iotqa: Improve guide on building/running tests

---

README.rst
meta-refkit/conf/distro/refkit.conf

README: add contribution guidelines

---

meta-iotqa/conf/test/minnowboardturbot.mask

meta-iotqa: Enable wifi and BT test for Minnowboard

---

Jenkinsfile

The email should look something like:
```
Git commit hash: 6cd5c6bef696cfa18b87739f072b1f4023e12739
Added commits:
Include 'common-test' features to all development profile images
meta-iotqa: Clean up wifi connect test
meta-iotqa: Enable wifi test
meta-iotqa: Disable wifi test for Minnowboard Turbot
Test results:
Image: refkit-image-common-intel-corei7-64-2017-03-06_23-48-15-build-349.wic
Device: 570x
Total:24  Pass:24  Fail:0  Skip:0  Error:0
Run rate:100%  Pass rate of total:100%  Pass rate of exec:100%
-------------------------------------------------------------------
Image: refkit-image-common-intel-corei7-64-2017-03-06_23-48-15-build-349.wic
Device: minnowboardturbot
Total:24  Pass:24  Fail:0  Skip:0  Error:0
Run rate:100%  Pass rate of total:100%  Pass rate of exec:100% …
```

Include a list of added commits to master build email

---

meta-iotqa/recipes-test/upm-test/upm-test_1.0.0.bb
meta-refkit/classes/buildhistory-extra.bbclass
meta-refkit/classes/refkit-image.bbclass
meta-refkit/conf/distro/include/refkit-ci.inc

intel-iot-refkit: submodule updates

---

README.rst
doc/profiles.rst

[skip-ci]
Replaces #67 
I've resolved conflicts due to #68 and added a couple of other doc updates/fixes.

doc updates

---

meta-refkit/recipes-opencl/beignet/beignet.inc
meta-refkit/recipes-opencl/beignet/files/0001-api-mark-platform-not-supported-if-device-is-not-fou.patch
meta-refkit/recipes-opencl/beignet/files/0001-reduced-native-for-1.3.1.patch

Update HEAD a bit over release 1.3.1 so that we get the patch which fixes Minnowboard Max OpenCL support.

beignet: update to 1.3.1.

---

Jenkinsfile
docker/publish-project.sh
docker/tester-exec.sh

Streamline and cleanup changes which do not cause noteworthy functional changes, but improve readability, reduce code lines and reduce unneeded parameter passing.

CI: streamline and cleanup changes

---

Jenkinsfile

Currently if there is an error in testing the email won't get sent. Move
the code block that sends the email under 'finally' so it always gets sent.
Also if testing has an error build result will stay as success.
Manually set it as 'FAILURE' if there is an error at any point of the
build and set it as 'UNSTABLE' if there is an error in testing (some problem with testing setup itself.

Always send master build email

---

doc/howtos/bluetoothspeaker.rst

Add documentation how to enable bluetooth speaker functionality

---

meta-refkit/classes/supported-recipes.bbclass
meta-refkit/conf/distro/refkit.conf

fix eSDK configuration

---

doc/howtos/qemu.rst
meta-refkit/conf/local.conf.sample

doc: add QEMU howto

---

docker/build-common-util.sh
docker/build-project.sh
docker/post-build.sh
docker/pre-build.sh

This enables auto.conf creation from multiple scripts

CI: refactor creation of auto.conf, use common functions

---

meta-refkit/conf/distro/include/refkit-supported-recipes.txt

Trying to figure out BitBake issues in #113.

Update oe-core and meta-oe.

---

doc/system-update.rst
docker/opensuse-42.2/Dockerfile
meta-refkit-core/classes/ostree-image.bbclass
meta-refkit-core/classes/ostree-sanity.bbclass
meta-refkit-core/classes/refkit-image.bbclass
meta-refkit-core/classes/refkit-sanity.bbclass
meta-refkit-core/conf/distro/include/refkit-config.inc
meta-refkit-core/lib/oeqa/selftest/cases/image_installer.py
meta-refkit-core/lib/oeqa/selftest/cases/refkit_ostree.py
meta-refkit-core/lib/oeqa/selftest/systemupdate/systemupdatebase.py
meta-refkit-core/lib/ostree/ostreeupdate.py
meta-refkit-core/recipes-images/images/refkit-initramfs.bb
meta-refkit-core/recipes-ostree/initramfs-framework-ostree/files/ostree
meta-refkit-core/recipes-ostree/initramfs-framework-ostree/initramfs-framework-ostree.bb
meta-refkit-core/recipes-ostree/refkit-ostree/refkit-ostree_git.bb
meta-refkit-core/wic/refkit-directdisk.wks.in
meta-refkit/conf/distro/include/refkit-ci.inc
meta-refkit/conf/distro/include/refkit-supported-recipes.txt

OSTree system update

---

meta-iotqa/conf/test/refkit-image-computervision.manifest
meta-iotqa/lib/oeqa/runtime/multimedia/gstreamer/gstreamer_cli.py

Retest gstreamer test case after rebase the branch.

meta-iotqa: add gstreamer commandline tests

---

doc/howtos/caffe.rst

Instructions for both OpenCV DNN and Caffe itself.

Document how Caffe models can be used.

---

meta-flatpak/classes/refkit-signing-keys.bbclass

meta-flatpak: fix bashism when incrementing 'slept' var.

---

.gitmodules
meta-refkit-core/conf/layer.conf
meta-refkit-gateway/README.rst
meta-refkit/conf/bblayers.conf.sample
meta-refkit/conf/layer.conf

We moved meta-iot-web layer to new repo to keep all web
component layers in one place, so this updates the remote
url of the meta-iot-web submodule.
Signed-off-by: Sudarsana Nagineni <sudarsana.nagineni@intel.com>

meta-iot-web: change url of meta-iot-web submodule

---

meta-refkit-core/classes/ostree-image.bbclass
meta-refkit-core/lib/oeqa/selftest/cases/refkit_ostree.py
meta-refkit-core/lib/oeqa/selftest/systemupdate/systemupdatebase.py
meta-refkit-core/lib/ostree/ostreeupdate.py
meta-refkit-core/recipes-selftest/images/refkit-image-update-ostree-modified.bb
meta-refkit-core/recipes-selftest/images/refkit-image-update-ostree.bb

ostree: some testing enhancements

---

Jenkinsfile

On a new refkit CI we attempt switching to Jenkins ghprb plugin from "GH integration".
ghprb plugin uses different names for GH variable values,
There is no intermediate status setting method so we skip these.
Note, this PR will build stat will remain yellow dot even after good build,
because status updates have been blocked in Jenkinsfile.
This is intentional.

CI Jenkinsfile: enable building on new refkit CI

---

Jenkinsfile

Combine two locks into one:
Move daft-tester xunit publish into finally-block,
net result should remain same.
That allows to combine two-in-row locked regions
and stop using 2nd lock.
2nd commit removes Github status setting code
which became unneeded/unused after move to different ghprb plugin

CI Jenkinsfile: streamline and shorten

---

meta-iotqa/lib/oeqa/runtime/multimedia/opencv/files/cv_capture_video.py
meta-iotqa/lib/oeqa/runtime/multimedia/opencv/files/cv_detect_shape.py
meta-iotqa/lib/oeqa/runtime/multimedia/opencv/files/cv_process_image.py
meta-iotqa/lib/oeqa/runtime/multimedia/opencv/files/cv_read_image.py
meta-iotqa/lib/oeqa/runtime/multimedia/opencv/opencv_cv2.py

Add comments to the main test suite and each
test cases.
Signed-off-by: Yeoh Ee Peng <ee.peng.yeoh@intel.com>

meta-iotqa: add comments to opencv python interface test suite

---

Jenkinsfile
docker/build-common-util.sh
docker/build-project.sh
docker/publish-project.sh
docker/tester-exec.sh
meta-refkit-core/lib/oeqa/selftest/cases/image_installer.py
meta-refkit/conf/distro/include/refkit-ci.inc

CI: update exclude set, publish and test multiple configs, "headless" main config

---

meta-refkit-core/conf/distro/include/refkit-config.inc

Remove gtk dependency from opencv

---

meta-iotqa/lib/oeqa/runtime/peripherals/mraa/mraa_gpio.py

Add tests for mraa-gpio python interface.
Signed-off-by: Ashwin Soman <ashwinx.soman@intel.com>

meta-iotqa:  add qa tests for mraa-gpio.

---

meta-iotqa/conf/test/refkit-image-computervision.manifest
meta-iotqa/lib/oeqa/runtime/multimedia/opencl/opencl.py

Add QA tests for OpenCL library and ICD files

meta-iotqa: Add QA tests for OpenCL

---

meta-iotqa/conf/test/refkit-image-computervision.manifest
meta-iotqa/lib/oeqa/runtime/multimedia/vaapi/test_vaapi_present.py

Add tests for multimedia/vaapi
Signed-off-by: Ashwin Soman <ashwinx.soman@intel.com>

meta-iotqa: add qa tests for VAAPI

---

meta-iotqa/conf/test/refkit-image-gateway.manifest
meta-iotqa/lib/oeqa/runtime/peripherals/mraa/mraa_i2c.py

Signed-off-by: nvelux <nagarajagopalx.velu@intel.com>
test case for data sending and receiving to rs232 port

meta-iotqa: add basic I2C bus testing

---

meta-refkit-computervision/recipes-computervision/packagegroups/packagegroup-computervision-test.bb
meta-refkit-core/bbappends/meta-intel/common/recipes-kernel/iwlwifi/iwlwifi_%.bbappend
meta-refkit-core/bbappends/meta-intel/common/recipes-kernel/linux/linux-intel_4.9.bbappend
meta-refkit-core/bbappends/meta-oic/recipes-core/iotivity/iotivity_%.bbappend
meta-refkit-core/bbappends/openembedded-core/meta/recipes-devtools/qemu/qemu_%.bbappend
meta-refkit-core/classes/refkit-image.bbclass
meta-refkit-core/conf/layer.conf
meta-refkit/conf/distro/include/refkit-group
meta-refkit/conf/distro/include/refkit-passwd
meta-refkit/conf/distro/include/refkit-supported-recipes.txt
meta-refkit/conf/distro/refkit.conf
meta-refkit/lib/oeqa/selftest/cases/refkit_poky.py

intel-iot-refkit: pull in latest changes

---

meta-refkit-core/bbappends/openembedded-core/meta/recipes-devtools/bmap-tools/bmap-tools-deploy.inc
meta-refkit-core/classes/refkit-image.bbclass

* bitbake 1ca2eec...ed3aab9 (5):
> toaster: update pyro to rocko as stable release
> toaster: handle early exceptions
> tests/fetch: handle network failures gracefully
> fetch2: add stub latest_versionstring to FetchMethod
> Replace deprecated git branch parameter "--set-upstream"
* openembedded-core cc319b6...2ebbeb6 (64):
> staging: gracefully abort if two recipes conflict in the sysroot
> devtool: upgrade: check that user has configured git properly
> go-helloworld: Use the Golang examples repository
> go-dep: Add 0.3.0 release
> go.bbclass: add GO_INSTALL_FILTEROUT variable
> go.bbclass: add do_unpack function to handle common cases
> go.bbclass: separate ${S} and ${B}
> go.bbclass: Use an auxiliary variable to add the build dependencies
> go.bbclass: exported function cleanup
> …

Refkit CI: pull in the latest changes

---

meta-refkit-core/classes/refkit-image.bbclass

Running bsdtar (for example, as part of swupd) needs a UTF-8 enabled
locale, otherwise one gets errors when unpacking archives with UTF-8
encoded file or link names.
refkit-image.bbclass disabled locales entirely. Now we use the usual
OE-core default (en-us en-gb at the moment).
In addition, the first one gets activated as system default by storing
it in /etc/locale.conf.

enhance locale support

---

meta-refkit-extra/conf/distro/include/refkit-extra-supported-recipes.txt
meta-refkit-extra/recipes-convnet/darknet/darknet_git.bb
meta-refkit-extra/recipes-convnet/darknet/files/0001-Makefile-added-a-soname-to-the-libdarknet.so.patch

Darknet is an open source neural network framework written in C.

darknet: added a new package.

---

meta-refkit/conf/distro/include/refkit-ci.inc

refkit-ci.inc: stop CI DAFT tests on 570x HW (Joule)
