intel/intel-iot-refkit

- meta-refkit/classes/refkit-image.bbclass
- meta-refkit/conf/distro/include/refkit-development.inc
- meta-refkit/conf/distro/include/refkit-supported-recipes.txt
- meta-refkit/recipes-computervision/packagegroups/packagegroup-computervision-test.bb
- meta-refkit/recipes-computervision/packagegroups/packagegroup-computervision.bb
- meta-refkit/recipes-image/images/refkit-image-computervision.bb
Add test configuration to computer vision profile. If the image is build in "development" mode, add interactive test and development packages. The initial test content is bit limited, but more is planned.
Also add libva-intel-driver and gstreamer-plugins-good to the computer vision images in both production and development mode. This enhances webcam support (by adding v4l2src element among other things) and enables HW acceleration of libva operations using Intel GPU backend.
> Computer vision profile test image configuration + better handling of web cameras to the main profile

- meta-refkit/classes/image-dsk.bbclass
- meta-refkit/classes/refkit-image.bbclass
This PR enables Runtime Machine Configuration (RMC) feature from meta-intel. It helps to apply board specific settings (e.g., kernel cmdline) runtime. In particular, we get the serial console information for the boards we're running.
> Enable RMC

- meta-iotqa/lib/oeqa/runtime/sanity/baseos.py
This error is random and doesn't seem to affect anything.
> meta-iotqa: Ignore net interface name changing error

- meta-refkit/recipes-security/openssh/openssh_%.bbappend
The openssh base package is empty. Having the iptables runtime
dependency there is useless, as the base package never gets
installed. Move the dependency to the proper -sshd subpackage.
Signed-off-by: Krisztian Litkey <krisztian.litkey@intel.com>
> openssh_%.bbappend: fix incorrect iptables dependency.

- Jenkinsfile
Publishing build results over rsync does not gain anything from being
run inside docker, but data path gets more complex and more risky
to introduce overhead and problems, so letäs reduce that complexity.
> CI Jenkinsfile: update GIT settings for CI user

- .gitmodules
- meta-refkit/conf/bblayers.conf.sample
- meta-refkit/conf/distro/include/refkit-supported-recipes.txt
- meta-refkit/recipes-computervision/librealsense/files/0001-examples-control-building-of-the-graphical-examples.patch
- meta-refkit/recipes-computervision/librealsense/files/0001-scripts-removed-bashisms.patch
- meta-refkit/recipes-computervision/librealsense/librealsense_%.bbappend
- meta-refkit/recipes-computervision/packagegroups/packagegroup-computervision-test.bb
- meta-refkit/recipes-computervision/packagegroups/packagegroup-computervision.bb
Add `meta-intel-realsense` layer. Fix librealsense recipe so that it compiles without X11 support. Patch librealsense itself so that we can drop bash runtime dependency and have non-graphical examples for testing and trying out librealsense. The local patches have been submitted to upstream, so in the future we might drop the three patches that change librealsense behavior.
> Add librealsense to computer vision profile.

- meta-iotqa/lib/oeqa/runtime/sanity/baseos.py
Add '\*ERROR\* dp aux hw did not signal timeout' to list of ignored
errors. This error happens randomly under 5% of the time and doesn't
seem to cause any additional errors in other tests. Tried to reproduce
the error with an image that it happened with but couldn't get it with 25
flash/test cycles. This error also doesn't seem to be easily fixed. So ignore this
error as it will cause tests to fail randomly.
> meta-iotqa: Ignore Minnowboard boot error

- meta-refkit/conf/distro/include/refkit-group
- meta-refkit/conf/distro/include/refkit-passwd
- meta-refkit/conf/distro/include/refkit-supported-recipes.txt
- meta-refkit/conf/distro/refkit.conf
- meta-refkit/recipes-core/base-passwd/files/group.master
- meta-refkit/recipes-multimedia/pulseaudio/pulseaudio_%.bbappend
Add pulseaudio to distro features and supported
recipes. Create also audio group and pulse user.
This commit doesn't include any pulseaudio packages
to the images.
> Pulseaudio: enable the use of pulseaudio packages

- meta-iotqa/conf/test/refkit-image-gateway.manifest
- meta-iotqa/lib/oeqa/runtime/sanity/pulseaudio.py
- meta-refkit/classes/refkit-image.bbclass
- meta-refkit/recipes-core/packagegroups/packagegroup-bluetooth-audio.bb
- meta-refkit/recipes-image/images/refkit-image-gateway.bb
Add pulseaudio and its bluetooth related modules
to gateway profile. Includes also a simple test to
check the existence of the daemon.
> Add bluetooth audio packages to gateway profile

- meta-iotqa/lib/oeqa/runtime/sanity/baseos.py
"Error changing net interface name..." and "probe of LNXPWRBN:00 failed"
are duplicates. Rest of them don't seem to be relevant anymore.
> meta-iotqa: Remove some ignored errors

- meta-iotqa/classes/test-iot.bbclass
If a new profile is added without adding a test manifest for it this part
of the code shouldn't cause an error.
> meta-iotqa: Check if profile test manifest exists

- meta-iotqa/conf/test/refkit-image-computervision.manifest
- meta-iotqa/lib/oeqa/runtime/computervision/realsense_headless.py
- meta-refkit/recipes-computervision/librealsense/librealsense_%.bbappend
Update meta-intel-realsense. Remove non-needed local patches. Add a simple validation test for the feature.
> meta-intel-realsense layer update.

- meta-iotqa/classes/test-iot.bbclass
Added a variable to allow the set of test cases in the generated
testplan to be extended dynamically during bitbake time. Simply
append the fully qualified name of test cases to IOTQA_EXTRA_TESTS
and they will be included in the test plan. Test cases are declared
in the form
```
tc1[,tc2[,tc3...]][:image1[,image2[,image3...]]]
```
An omitted image or an explicit '*' will match all image (profile) names.
For example, here's how to conditionally include an extra test in refkit-image-minimal:
```
IOTQA_EXTRA_TESTS_append = " \
${@bb.utils.contains('FINGERNAILS', 'long-sharp-sticks', \
'oeqa.runtime.sadistic.test:refkit-image-minimal', '', d)} \
"
```
or here is how to include extra tests in several images (profiles):
```    
IOTQA_EXTRA_TESTS_append = " \ …
```
> test-iot.bbclass: let the set of test cases be extended bitbake-time.

- meta-refkit/lib/image-dsk.py
In order to properly copy rmc.db and other EFI partition contents,
remove explicit EFI subfolder copy and instead copy all boot/ contents
to the EFI partition. Also make the EFI partitions larger to properly
fit all the contents and the total image size 64 MB under 4 GB.
> Remove explicit EFI subfolder copy when creating a FAT partition

- meta-refkit/classes/image-dsk.bbclass
- meta-refkit/classes/refkit-image.bbclass
- meta-refkit/wic/refkit-directdisk.wks.in
They were inconsistent and too small for future use cases.
Replaces PR #36 and needed for PR #19, which already had commit
13829d8.
> image: adjust partition sizes

- meta-iotqa/lib/oeqa/runtime/sanity/baseos.py
The error: "/usr/sbin/alsactl: state_lock:125: file
/var/lib/alsa/asound.state lock error: File exists" happens randomly under 2% of
the time so it's really hard to replicate and test if it affects
anything. Also there seems to be no fix for it so ignore the error.
> meta-iotqa: Ignore one alsa boot error

- meta-iotqa/conf/test/refkit-image-common.manifest
- meta-iotqa/lib/oeqa/runtime/sanity/mraa_gpio.py
These tests will set a GPIO pin on and off and check the output with BeagleBone that it works.
> Add and enable mraa GPIO tests

- Jenkinsfile
- docker/publish-project.sh
Sometimes detailed build logs contain important information
which gets lost after failed build phase because we stop the pipeline.
Let's run publish part always, trying to copy out whatever we can.
> CI Jenkinsfile: attempt publish even after build failure

- doc/hardware.rst
Add a document listing supported validated and tested hardware and
potential known pending hardware support items.
> Add hardware support specification

- docker/tester-exec.sh
xz-compressed image can be uncompressed from pipe.
so we can pipe it from wget to unxz without writing to file.
We need to test for existence using -s now because
missing file in server will show as zero-size file locally.
Also, reduce variables use in images download code.
> CI tester-exec: avoid double write of xz image

- docker/tester-exec.sh
Report masked tests as 'N/A'. Don't sum masked tests to skipped tests. This way run rate and pass rate of total will be 100% if there is masked tests but no skipped ones. Also change '/home/tester' to $HOME variable which makes this script more portable.
> tester-exec.sh: Minor changes

- meta-iotqa/lib/oeqa/runtime/sanity/mraa_gpio.py
Adding the output from the command should help understand why this test
fails when it does.
> mraa_gpio.py: Add mraa-gpio command output to fail message

- README.rst
local-build.sh allows to build just subset of images, but we don't
mention this possibility in README.
If started without arguments, target image list is parsed from 
CI settings and will include
all images used in CI, plus test suites.
> README.rst: mention possibility to give argument to local build

- meta-iotqa/README.md
- meta-iotqa/lib/runtest.py
In case of testing a QEMU-based target it might be easier to
use SLIRP networking which doesn't require root permissions to
create a TAP network interface. But it means that the target can
be accessible only via a port forwarded to the host's loopback
interface. And as the default SSH port is usually taken already
the target's SSH port is forwarded to port 2222 on localhost.
Unfortunately the runtest.py script assumes that the SSH
port is 22 always.
This patch extends runtest.py options to accept an optional
port argument. So the command to run tests on a QEMU target
may look like the following:
runtest.py -f testplan/refkit-image-common.manifest -m intel-corei7-64 -t 127.0.0.1:2222 -s 10.0.2.2
> meta-iotqa: extend runtest.py to accept target's port number

- meta-refkit/recipes-sensors/mraa/files/0001-mraa.c-Fix-strsep-crash.patch
- meta-refkit/recipes-sensors/mraa/mraa.inc
The patch has been merged already upstream. Problem was caused by not
freeing a variable correctly.
> mraa: Add patch to fix mraa-gpio randomly crashing

- Jenkinsfile
- docker/build-project.sh
- docker/post-build.sh
- docker/pre-build.sh
- meta-refkit/conf/distro/include/refkit-ci.inc
- meta-refkit/lib/oeqa/selftest/iotsstatetests.py
First 5 commits are re-factoring of Jenkinsfile, as I prepared to introduce separate stage where prebuild
would run. 
After that done, I was advised to insert prebuild test in build script. 
That was done in 6th commit.
Commit 7 drops use of ssh-agent on docker session as we seem to get repos accessed without it.
Then the plan changed again and pre- and -post steps were added as separate stages and scripts
in commits 8,9 with build step un-parallelised (one MACHINE).
This restored some stages taken away in refactoring.
Commit 11 clarifies build script parts by moving some more sub-steps to CI-only sections, freeing
local build from CI and tester related steps.
last commit 12 moves enablement of BUILDHISTORY from refkit-ci.inc into build-project.sh, thus freeing
refkit-ci.inc to be used in …
> CI: run oe-selftests as pre-build, post-build steps

- docker/build-project.sh
Recent change moved creation of ci_git_commit into later block
which runs after env-init, so that file was created one directory
level deeper, in build/ directory. But as other parts look for
file at top level of WORKSPACE, thise broke master build
where this file is used for summary message.
Code is safer if we spefify full path in writing.
> CI build-project.sh: fix location of ci_git_commit file

- meta-refkit/classes/refkit-image.bbclass
- meta-refkit/classes/refkit-swupd-image.bbclass
- meta-refkit/wic/refkit-directdisk.wks.in
We don't even have meta-swupd in refkit, so it makes more sense to
leave distro settings at their defaults instead of enabling
swupd-related tweaks in all cases.
> remove swupd tweaks from default build

- meta-refkit/classes/refkit-image.bbclass
- meta-refkit/conf/distro/include/refkit-supported-recipes.txt
In order to fully support machine functionality provided by BSPs,
install machine specific extra packages to the image.
> Install machine specific packages to images

- meta-refkit/classes/refkit-image.bbclass
- meta-refkit/conf/distro/refkit.conf
- meta-refkit/recipes-core/os-release/os-release.bbappend
Currently, our DISTRO_VERSION is set to a misleading value and is not even
updated regularly. As we are working in a (partially) rolling-release mode,
any "point release" versioning does not make much sense.
Use static DISTRO_VERSION that gives no indication of any specific version.
> refkit: use static DISTRO_VERSION

- README.rst
Fix a broken link, remove ".. note::" as github doesn't format it
nicely and write ":file:`conf/local.conf`" the same way other files
are written in the readme.
> README.rst: Small fixes

- docker/tester-exec.sh
Variables were initialized one-by-one to avoid error
on use as -u is used in shell. This consumes unneccessary code
lines but also creates meaningless job log files, so combine
multiple vars into declare stmt. Also, utilize += in adding.
Unused legacy code lines about older devices can be removed
> CI tester-exec.sh: streamline and reduce unused legacy code

- meta-refkit/classes/imagevariant.bbclass
Don't go into infinite recursion for trivial namespace collision of
variants and IMAGE_FEATUREs. This happens when a variant contains an
IMAGE_FEATURE with an identical name. For instance the following sample
would fail without this patch, recursing on expanding flatpak until
the maximum recursion depth is exceeded:
```
...
IMAGE_FEATURES[validitems] += " \
flatpak \
tools-sdk dev-pkgs tools-debug tools-profile \
"
FEATURE_PACKAGES_flatpak = " \
packagegroup-flatpak \
${@'flatpak-predefined-repos' \
if d.getVar('FLATPAK_APP_REPOS') else ''} \
"
...
IMAGE_VARIANT[flatpak] = "flatpak"
IMAGE_VARIANT[flatpak-sdk] = "flatpak tools-develop tools-debug dev-pkgs"
BBCLASSEXTEND = "imagevariant:flatpak imagevariant:flatpak-sdk"
```
Note that we only handle reasonable to be expected trivial …
> imagevariant.bbclass: handle trivial variant/feature name collisions.

- meta-iotqa/conf/test/refkit-image-common.manifest
- meta-iotqa/conf/test/refkit-image-gateway.manifest
- meta-refkit/classes/refkit-image.bbclass
iotivity is not something all profile images need to share.
Keep it in gateway for now and move it out from common.
> refkit-image: move iotivity out from common

- meta-refkit/classes/refkit-image.bbclass
- meta-refkit/conf/distro/refkit.conf
Mounting as read-only was enforced with the argument that then
fsck can be applied to the rootfs, but exactly that was explicitly
disabled in the distro configuration.
Disabling fsck makes sense, but that is better set in the image class,
and then we can also directly mount rw (avoids a remount, better for a
stateless image, for example because we don't need the empty
/etc/machine-id).
Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>
> refkit images: mount read/write by default

- meta-refkit/classes/buildhistory-extra.bbclass
The previous approach of leaving ${S} and ${BASE_WORKDIR} unchanged in
source URLs fails for ovmf which embedds ${S} in a more complex
expression:
${@bb.utils.contains('PACKAGECONFIG', 'secureboot', 'http://www.openssl.org/source/openssl-1.0.2j.tar.gz;name=openssl;subdir=${S}/CryptoPkg/Library/OpensslLib', '', d)}
When expanding ${S} fails because it is unset, the entire expression
is left unexpanded, which then causes parser errors because it isn't
a valid URL.
So instead, now we replace ${S} with S, leading to entries in the
build history like this:
http://www.openssl.org/source/openssl-1.0.2j.tar.gz;name=openssl;subdir=S/CryptoPkg/Library/OpensslLib intel-corei7-64/downloads/openssl-1.0.2j.tar.gz e7aff292be21c259c6af26469c7a9b3ba26e9abaaffd325e3dccc9785256c431
Same for BASE_WORKDIR. …
> buildhistory-extra.bbclass: allow expansion of S and BASE_WORKDIR

- meta-refkit/conf/distro/refkit.conf
- meta-refkit/recipes-devtools/python/python3_%.bbappend
Compile Python 3 without readline, gdbm, and db support. This removes the need for GPLv3 depedencies.
The patch was submitted upstream (https://patchwork.openembedded.org/patch/136368/) but never merged. This is the `.bbappend` version of it.
> Reduce Python 3 dependencies

- meta-iotqa/lib/oeqa/runtime/sanity/comm_btcheck.py
At the start of Bluetooth testing, Bluetooth is getting enabled so after
tests are done it should be disabled again so it doesn't interfere with
other tests. For some reason WiFi test takes about 2 minutes longer with
Minnowboard if Bluetooth isn't disabled after Bluetooth test is done.
Also remove a command that is only for Edison (which isn't supported).
> meta-iotqa: After Bluetooth test disable Bluetooth

- Jenkinsfile
- docker/tester-exec.sh
Streamline, cleanup, restructure.
5. commit solves the recently found issue of missing xUnit result blocks in some CI jobs
> CI Jenkinsfile,tester-exec: streamline, fix issue of lost test results

- meta-refkit/conf/distro/refkit.conf
- meta-refkit/recipes-connectivity/bluez5/bluez5_5%.bbappend
The reason behind this is to eventually remove libreadline from our images with production configuration.
> Remove readline support from bluez5

- meta-iotqa/lib/oeqa/runtime/sanity/pulseaudio.py
Add a new test that checks that necessary modules are loaded for
PulseAudio.
> meta-iotqa: Improve PulseAudio testing

- docker/publish-project.sh
Publish script failed if isafw-logs/ was present but
isafw-reports dirs were not yet created, added proper
checks and publish for both parts.
Note: this adds publish of isafw logs, which we did not
publish before.
> CI publish-project: handle isafw logs,reports better

- meta-refkit/recipes-opencl/beignet/beignet.inc
This prevents `ld: cannot find -ltinfo` error when building beignet.
> beignet: add ncurses dependency.

- meta-refkit/conf/distro/include/refkit-supported-recipes.txt
Whitelist realtime kernel variants to support timing critical tasks.
> Add support for realtime kernels

- meta-refkit/recipes-devtools/qemu/qemu_%.bbappend
Usage of SRC_URI_remove_pn-qemu-native, limits the patch removal only for native
builds, where it should apply even for nativesdk builds.
Signed-off-by: Amarnath Valluri <amarnath.valluri@intel.com>
> qemu: Do not limit TPM CUSE driver removal to only native builds

- meta-refkit/conf/distro/refkit.conf
- meta-refkit/recipes-devtools/python/python_%.bbappend
This is a temporary solution until https://github.com/intel/intel-iot-refkit/pull/109 is merged. The mechanism follows closely similar modification to Python3 in https://github.com/intel/intel-iot-refkit/pull/92.
> Configure Python2 to drop GPLv3 dependencies.

- doc/howtos/image-install.rst
- meta-refkit/conf/distro/include/refkit-ci.inc
- meta-refkit/conf/distro/refkit.conf
- meta-refkit/lib/oeqa/selftest/image-installer.py
- meta-refkit/scripts/image-installer/init-tpm
- meta-refkit/scripts/image-installer/runqemu-install
- meta-refkit/scripts/image-installer/runqemu-internal-disk
This fixes the problem with swtpm-wrappers and usrmerge by renaming it
to swtpm-wrappers-native. Not following that naming convention had
some real effect on DISTRO_FEATURE handling.
* meta-security 6674749...3bcca12 (4):
> swtpm-wrappers: fix naming convention violation
> tpm2.0-tss: update to tip.
> samhain: update to 4.2.1
> swtpm: update to latest tip
Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>
> meta-security: update submodule to fix usrmerge

- meta-refkit-extra/conf/distro/include/refkit-extra.conf
- meta-refkit-extra/recipes-convnet/boost/boost_%.bbappend
Do not have Boost PACKAGE_CONFIG variable set in a .bbappend file, because adding or removing layers should not affect the build result. Have the configuration setting instead in layer's distro config file.
> meta-refkit-extra: move Boost package config to configuration file.

- docker/build-project.sh
- docker/post-build.sh
We can check that the script changes do not break the build when
testing the PR, but we will have to merge and run a master build
before we'll know what's slowing down the master builds.
> compare sstate signatures between main build and post-build

- docker/post-build.sh
The previous attempt did not show anything useful from the time before
oe-selftest. Let's try also after the command.
> compare sstate signatures between main build and post-build, part II

- Jenkinsfile
- docker/build-common-util.sh
- docker/build-project.sh
- docker/post-build.sh
"Keep workspaces" brings 2 improvements:
- workspaces from few previous builds are present, allowing
to check for state even after next build in same worker started;
- deletion of older build trees does not take time of next build,
it is performed by async-runned cleanup job.
Deletion of older workspaces is done after build in parallel with tester jobs,
scheduled in the same builder which performed build stage.
Additionally, this PR has smaller simplification in 1st commit,
2 simplifications related to single-MACHINE build in commits 4 and 5,
one status print shortening in commit 6,
one variable-defined-once improvement in commit 7.
Commits 8 and 9 deal with post-build test recently surfaced needs.
> CI Jenkinsfile: keep build workspaces with later off-build-path deletion

- meta-refkit/conf/distro/include/refkit-group
- meta-refkit/conf/distro/include/refkit-passwd
Required crontab when enable tools-sdk and tools-testapps
in REFKIT_IMAGE_EXTRA_FEATURES
Signed-off-by: Choong YinThong <yin.thong.choong@intel.com>
> Crontab: Added crontab into refkit_passwd and refkit_group

- meta-refkit/conf/distro/include/refkit-supported-recipes.txt
- meta-refkit/recipes-opencl/beignet/beignet-550x_git.bb
- meta-refkit/recipes-opencl/beignet/beignet-570x_git.bb
- meta-refkit/recipes-opencl/packagegroups/packagegroup-opencl.bb
550x board GPU has a different PCI ID than 570x. Add a new beignet recipe to support it.
> beignet-550x: add new recipe.

- meta-iotqa/README.md
- meta-iotqa/classes/test-iot.bbclass
Depending on if `do_test_iot_export` task is done with or without docker the directory name inside created testsuite tarball will differ. So just use specific name with it ("iottest"). Also improve meta-iotqa/README.MD.
> meta-iotqa: Use fixed dir name inside testsuite tarball and improve readme

- meta-iotqa/lib/oeqa/runtime/core/baseos/baseos.py
Message "*ERROR* dp_aux_ch not done status 0xa1450064"
is randomly present in few percent of test runs.
Remove alsa error msg not spotted in last CI PR 500 runs
> meta-iotqa: modify allowed errors whitelist

- meta-refkit-computervision/recipes-opencl/beignet/beignet.inc
Enable parallel build for beignet by fixing cmake dependencies. Also remove host contamination possibilities by using Python from sysroot instead of Python from build host. This should also help with the incompatible host clang version problem. Also update beignet to use the latest git HEAD.
> Clean up beignet recipe

- meta-refkit-core/recipes-core/packagegroups/packagegroup-core-connectivity.bb
The /etc/nsswitch.conf file lists the myhostname plugin
as enabled for resolving hostnames, but all Refkit images
lack it. This makes commands like
$ ping `hostname`
fail.
Include the plugin in the core connectivity configuration.
Fixes: [YOCTO #11588]
Signed-off-by: Dmitry Rozhkov <dmitry.rozhkov@linux.intel.com>
> packagegroup-core-connectivity.bb: include libnss-myhostname

- meta-refkit-core/recipes-core/packagegroups/packagegroup-python-runtime.bb
- meta-refkit-core/recipes-devtools/python/refkit-python.inc
After dropping gdbm and db from DEPENDS, we also need to
make sure the corresponding ${PN}-* packages don't get
added in PACKAGES/PROVIDES/RDEPENDS.
Without this, the package managers run into dependency issues
when installing, e.g., python(3)-modules that depend on
existent packages.
While we're at it, it's good time to move python-runtime image
feature to use Python3.
> python: runtime and packaging changes

- meta-refkit-core/recipes-sensors/mraa/mraa_git.bb
- meta-refkit-core/recipes-sensors/upm/upm_git.bb
mraa update version from 1.6.0 to 1.7.0
upm update version from 1.1.0 to 1.3.0
Signed-off-by: Choong YinThong <yin.thong.choong@intel.com>
> mraa & upm: Updated to latest version

- meta-refkit-computervision/recipes-image/images/refkit-image-computervision.bb
- meta-refkit-core/conf/distro/include/refkit-config.inc
- meta-refkit-core/recipes-connectivity/avahi/avahi_%.bbappend
- meta-refkit-core/recipes-connectivity/bluez5/bluez5_5%.bbappend
- meta-refkit-core/recipes-images/images/refkit-image-common.bb
- meta-refkit-gateway/recipes-image/images/refkit-image-gateway.bb
- meta-refkit/lib/oeqa/selftest/cases/refkit_poky.py
Signed-off-by: Tuomas Katila <tuomas.katila@intel.com>
> append: fix two errors in _append rules; one in avahi and one in systemd

- meta-iotqa/conf/test/refkit-image-common.manifest
- meta-iotqa/conf/test/refkit-image-gateway.manifest
- meta-refkit-core/classes/refkit-image.bbclass
- meta-refkit-core/lib/oeqa/selftest/cases/image_installer.py
- meta-refkit-gateway/recipes-image/images/refkit-image-gateway.bb
Nothing major, just the removal of mraa/upm/NodeJS from
refkit-image-common that Mikko proposed in PR #184 and another
enhancement that I found useful.
> test enhancements

- doc/howtos/yocto-compatible.rst
This targets developers and explains how layers meet the "Yocto
Compatible 2.0" criteria and provide optional functionality to other
distributions.
> yocto-compatible.rst: implementation documentation

- Jenkinsfile
1. Cleanup of older build trees was not reliable.
Cleaning should run in early stage (using parallel stmt to avoid blocking other activity).
Previous way, running it later in parallel with on-device testing created 2 problems:
- in case of queued runs, same slot got busy with another job before cleaning thread,
which caused dummy wait of current job by length on another, newly started job:
- in case of failure during post-build, cleanup was not run at all,
which risked filling builder disks after repeated failures on same node.
> CI: fix cleanup of older build directories

- meta-iotqa/conf/test/refkit-image-computervision.manifest
- meta-iotqa/lib/oeqa/runtime/multimedia/opencv/opencv_dnn_1.py
- meta-refkit-computervision/recipes-computervision/caffe-bvlc-reference/caffe-bvlc-reference_0.1.bb
- meta-refkit-computervision/recipes-computervision/caffe-bvlc-reference/files/change_input_format.patch
- meta-refkit-computervision/recipes-computervision/caffe-bvlc-reference/files/dnn-test.py
- meta-refkit-computervision/recipes-computervision/packagegroups/packagegroup-computervision-test.bb
- meta-refkit-core/bbappends/meta-openembedded/meta-oe/recipes-support/lvm2/lvm2_%.bbappend
- meta-refkit-core/conf/distro/include/refkit-config.inc
- meta-refkit/conf/distro/include/refkit-supported-recipes.txt
OpenCV DNN module, update of meta-openembedded (to fix compilation issues), and a test for DNN.
> OpenCV DNN module and test

- meta-refkit-core/scripts/lib/wic/plugins/source/dm-verity.py
wic was reorganized, so this particular update has to be done in
combination with updating the dm-verity.py wic plugin.
There's no particular need for the update, I just happened to notice
that further work is needed and thus did it.
> openembedded-core submodule update

- meta-flatpak/classes/flatpak-repository.bbclass
- meta-iotqa/conf/test/refkit-image-gateway.manifest
- meta-refkit-gateway/README.rst
- meta-refkit-gateway/recipes-image/images/refkit-image-gateway.bb
- meta-refkit/conf/distro/include/refkit-ci.inc
This patch set enables flatpak support for the stock gateway image. IOW it essentially turns the stock refkit-image-gateway into refkit-image-gateway-flatpak-runtime, as long as the required flatpak distro features are enabled. Consequently, the patches also remove building and testing the explicitly spelled out flatpak variant of the same image in CI.
> flatpak-enable the stock gateway image

- meta-refkit-core/conf/distro/include/refkit-config.inc
- meta-refkit/conf/distro/refkit.conf
Setting ROS_USE_PYTHON3 in refkit-config.inc is better because:
- other distros may also need that setting
- all content re-configuration is one one place and thus
easier to review
Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>
> refkit: reconfigure meta-ros in refkit-config.inc

- meta-refkit-core/lib/oeqa/selftest/cases/image_installer.py
- meta-refkit-core/lib/oeqa/selftest/cases/refkit_license_check.py
- meta-refkit-core/lib/oeqa/selftest/systemupdate/systemupdatebase.py
- meta-refkit/conf/distro/include/refkit-ci.inc
- meta-refkit/lib/oeqa/selftest/cases/refkit_poky.py
- meta-refkit/lib/oeqa/selftest/cases/secureboot.py
With the recently enhanced runCmd/bitbake() in OE-core master we can get
output from the invoked command passed through the logger that each test
has, which provides much nicer output while a test runs: instead of of test
that just seems to hang, one gets a constant stream of messages with time
stamps.
The command also gets logged, so we can remove some extra output which now
is a bit redundant.
> log command output

- Jenkinsfile
- docker/build-project.sh
- docker/opensuse-42.2/Dockerfile
- docker/pre-build.sh
- docker/tester-create-summary.sh
- docker/tester-exec.sh
python3-unittest-xml-reporting and python-six packages are needed in Docker session
to make XML test-reports to be saved from post-tests.
In Jenkinsfile we will publish TEST-*.xml files produced in post-build stage.
Better git values handling: Create git ci_commit_id and commit list after check-out,
remove cross-layer-use of ci_git_commit
> CI: add pre- and post-test results publish and reporting

- meta-refkit-core/bbappends/openembedded-core/meta/recipes-core/util-linux/util-linux_%.bbappend
Upstream OE-core has this fix for the issue:
commit 07d6d0fb4dc689008bb0022d7d2ecc890c9159e5
Author: Amarnath Valluri <amarnath.valluri@intel.com>
Date:   Tue Jan 24 16:07:20 2017 +0200
util-linux,shadow: Make 'nologin' alternative command
Both shadow and util-linux packages provides 'nologin' binary in ${base_sbindir}
and ${sbindir} respectively, this leads to conflict when 'usrmerge' feature is
enabled, where ${sbindir} == ${base_sbindir}. Hance, handle this to alternative
system to resolve the conflict.
Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>
> util-linux_%.bbappend: remove obsolete nologin workaround

- meta-refkit-computervision/recipes-computervision/librealsense/files/0001-Add-missing-includes-for-functional.patch
- meta-refkit-computervision/recipes-computervision/librealsense/librealsense_%.bbappend
- meta-refkit-core/conf/distro/include/refkit-config.inc
- meta-refkit-gateway/recipes-core/iotivity/files/0001-resource-Include-functional-header-for-g-7.1.0.patch
- meta-refkit-gateway/recipes-core/iotivity/iotivity_%.bbappend
Many fixes (including meta-ros GCC7.1 readiness) have been merged
so move back to follow OE-core default GCCVERSION.
> Move to gcc 7.1

- docker/publish-project.sh
publishing of plain .wic files to storage server
takes majority of transfer time and also space on server,
but there is no use for stored plain .wic files as wic.xz
are used.
> CI: skip storing of plain .wic files

- docker/opensuse-42.2/Dockerfile
- meta-refkit-core/lib/oeqa/selftest/cases/refkit_ostree.py
Usage of the host netcat can be replaced by building socat-native.
Should fix PR #221.
> avoid netcat dependency

- Jenkinsfile
CI Jenkinsfile: Run post-build and DAFT tests in parallel
We can't keep same docker container around for another node stmt,
but we can create a new docker container, which will
use same worktree from build stage. That allows to
put post-build tests into same set with daft-based tests
and run all of those in parallel, thus shortening
the job time by daft-tests duration (which is shorter than
post-build tests duration).
Second change in this PR is:
Stop calling workspace cleaning a stage.
After async. cleanup was introduced, deleteDir at start of
each job does practically nothing, but we keep it there just in case.
There is no point however put this short duration up on stages chart.
> CI Jenkinsfile: Run post-build and DAFT tests in parallel

- meta-iotqa/conf/test/minnowboardturbot.mask
- meta-iotqa/conf/test/qemu.mask
- meta-iotqa/conf/test/refkit-image-common.manifest
- meta-iotqa/lib/oeqa/runtime/connectivity/bluetooth/bluetooth.py
- meta-iotqa/lib/oeqa/runtime/connectivity/bluetooth/bt_6lowpan.py
- meta-iotqa/lib/oeqa/runtime/connectivity/bluetooth/bt_6lowpan_mnode.py
- meta-iotqa/lib/oeqa/runtime/connectivity/bluetooth/bt_command.py
- meta-iotqa/lib/oeqa/runtime/connectivity/bluetooth/bt_command_mnode.py
- meta-iotqa/lib/oeqa/runtime/connectivity/bluetooth/bt_stability.py
- meta-refkit-core/classes/refkit-image.bbclass
This PR cleans up and includes single-node Bluetooth test cases in the refkit-image-common manifest (this is tracked on Yocto bug #11255). It also adds bluetoothctl back to development images as some of the enabled test cases make use of this tool.
This PR replaces https://github.com/intel/intel-iot-refkit/pull/116
> meta-iotqa: Clean up and enablement of single-node Bluetooth test cases

- Jenkinsfile
- docker/publish-project.sh
- docker/publish-sstate.sh
- docker/tester-create-summary.sh
- docker/tester-exec.sh
It makes sense to retry daft after unstable
result which means problem on tester.
2nd commit here is adding forgotten shebang in tester-create-summary.sh
which created trouble on Ubuntu where this script goes through dash
3rd commit fixes xml-reports handling which got partially broken with
recent parallel-testing change
4th commit is "publish sstate after post-build tests as well"
which was combined into this PR from PR#239
> CI: retry daft after unstable, fix bashism in summary, fix xml-reports handling, publish more sstate

- meta-flatpak/recipes-flatpak/flatpak/flatpak_git.bb
- meta-flatpak/recipes-ostree/ostree/ostree_git.bb
Update ostree to v2017.8.
Update flatpak to 0.9.7.
> Update ostree and flatpak to the latest tagged upstream releases.

- meta-iotqa/lib/oeqa/runtime/connectivity/wifi/wifi.py
DAFT test for testing wifi connection sometimes randomly fails. This fix forces the wifi test to retry at least 2 times before failing.
Signed-off-by: Christian da Costa <christian.da.costa@intel.com>
> meta-iotqa: modify wifi test to retry incase of error

- docker/build-project.sh
- docker/post-build.sh
- meta-refkit-core/classes/supported-recipes.bbclass
- meta-refkit-core/lib/supportedrecipes.py
- meta-refkit-core/recipes-selftest/images/refkit-image-common-wayland.bb
- meta-refkit-core/recipes-selftest/images/refkit-image-common-x11.bb
- meta-refkit/conf/distro/refkit.conf
Regressions have not been noticed unless someone manually built images with
graphics. We need to do at least build testing, and ideally produce images
that then can also be tested with DAFT.
multiconfig enhancements for supportedrecipes are needed to catch the usage of xf86-video-mga@openembedded-layer.
> CI: build also x11 and wayland images

- docker/build-project.sh
- docker/post-build.sh
We no longer have unexpected rebuilds, so we can remove the debug code
that was added for debugging those rebuilds. Makes the build a bit
faster again.
> CI: remove sstate debug code

- README.rst
[skip-ci]
This tag is misspelled so it does not work.
Linking to this chapter works nevertheless, because
of implicit links to chapter headings.
(If we want to have explicit link as was original intention,
we can put this line back in corrected form)
> [doc only] README: delete misspelled hyperlink tag

- meta-refkit-core/bbappends/openembedded-core/meta/recipes-core/initrdscripts/initramfs-framework_%.bbappend
One additional change on top of PR #248:
"initramfs-framework: include install-efi module in recipe for
installation" introduces an undesirable, hard dependency on parted. We
work around that after alerting the author about the problem.
> Refkit CI: pull in the latest changes

- meta-refkit/conf/distro/include/refkit-supported-recipes.txt
Due to recent BSP changes, new package iwlwifi needs to be added
to the whitelist.
> refkit-supported-recipes.txt: whitelist iwlwifi

- meta-refkit-core/bbappends/openembedded-core/meta/recipes-multimedia/pulseaudio/pulseaudio_%.bbappend
Remove consolekit run time dependency, because refkit is not
using it anyway. We are using systemd/logind which makes
consolekit obsolete.
> Remove pulseaudio rdepending on console kit

- meta-refkit/conf/distro/include/refkit-supported-recipes.txt
Whitelist libraries needed by librealsense X11 support. This is needed
for the computervision image to build with X11 support.
> refkit-supported-recipes.txt: whitelist librealsense x11 dependencies

- meta-refkit-extra/doc/computervision.rst
- meta-refkit-extra/recipes-convnet/caffe/caffe_git.bb
- meta-refkit-extra/recipes-convnet/caffe/files/0001-Allow-setting-numpy-include-dir-from-outside.patch
- meta-refkit-extra/recipes-convnet/caffe/files/0002-cmake-do-not-use-SYSTEM-for-non-system-include-direc.patch
- meta-refkit-extra/recipes-convnet/caffe/files/0003-cmake-fix-RPATHS.patch
- meta-refkit-extra/recipes-convnet/caffe/files/0004-config-use-Python-3.patch
- meta-refkit-extra/recipes-convnet/caffe/files/0005-io-change-to-imageio.patch
- meta-refkit-extra/recipes-convnet/caffe/files/0006-classify-demo-added-a-demo-app-for-classifying-image.patch
- meta-refkit-extra/recipes-convnet/caffe/files/0007-net_gen.py-fix-Python-3-compatibility.patch
- meta-refkit-extra/recipes-convnet/hdf5/files/configuration.patch
- meta-refkit-extra/recipes-convnet/hdf5/files/copy_generated.patch
- meta-refkit-extra/recipes-convnet/hdf5/files/generation.patch
- meta-refkit-extra/recipes-convnet/hdf5/hdf5_1.8.19.bb
- meta-refkit-extra/recipes-convnet/lmdb/files/0001-Patch-the-main-Makefile.patch
- meta-refkit-extra/recipes-convnet/lmdb/lmdb_0.9.21.bb
- meta-refkit-extra/recipes-convnet/python-imageio/python3-imageio_2.2.0.bb
- meta-refkit-extra/recipes-convnet/python-pillow/python3-pillow_4.1.1.bb
- meta-refkit-extra/recipes-convnet/python-protobuf/python3-protobuf_3.3.0.bb
Updated versions for several components needed when using Caffe from Python. Cleaned also the Caffe recipe a bit, and reorganized example model sharing with OpenCV DNN. HDF5 was broken before this PR, because when the new version was released, the previous version was no longer available for download (at least from the same URL).
> Convolutional network component upgrades.

- Jenkinsfile
- docker/publish-project.sh
- docker/tester-exec.sh
1st commit:  narrow archived xml file set to TEST-*.xml in Jenkinsfile
Mask used to be *.xml causing over-archiving of results.xml
from every tester with latest one remaining in archive,
which was misleading as it appears different each time because it 
typicaly comes from different tests.
results.xml is not used for anything so leave it out.
2nd commit: : Check for failure pattern in daft log file in tester-exec and show containing file.
Show DAFT-stage errors in main level job log instead of explanation remaining buried in 
one of many artifacts from DAFT,  which needs locating and opening one-by-one in job artifacts area.
Note that same error is typically shown in results-runtest.*.log
and in test_aft.*.log, we show results-runtest*.log which is shorter.
3rd commit: rsync can remove …
> CI: expose daft error, stop storing licenses in PR case, support multiple mail recipient lists, misc.cleanup

- meta-refkit-computervision/recipes-computervision/caffe-bvlc-reference/files/dnn-test.py
OpenCV 3.3 (in meta-openembedded master) has API changes in DNN module. Fix the tests to work with the latest API. Pull in latest meta-openembedded to get OpenCV 3.3.
> OpenCV 3.3 fixes + meta-openembedded master

- Jenkinsfile
Recent reduction of predefined variables was verified in PR
build only, and slipped through a regression failing master
build in CI where ci_pr_num does not get value and thus
remains undefined variable.
> CI Jenkinsfile: need ci_pr_num declared in master build

- .gitmodules
meta-clang master moved to clang 5.0 release branch but
beignet fails to build with it so move to use meta-clang
pyro branch that has 4.0.
> refkit: move to meta-clang pyro branch

- meta-refkit/conf/distro/include/refkit-supported-recipes.txt
openembedded-core (currently in master-next) moved to openssl 1.1 but added
openssl10 recipe for backwards compatibility (some recipes, like openssh,
need it).
Add the new openssl10 recipe in supported recipes to be able build it.
> supported-recipes: add openssl10

- meta-refkit-core/conf/distro/include/refkit-config.inc
In order to work with Secure Boot requirement, reduce the need for (L)GPLv3 components.
This is done by recompiling components with different configuration parameters,
reducing functionality, and leaving components out from the production images
[REFKIT #11494]
Signed-off-by: Choong Yin Thong <yin.thong.choong@intel.com>
> refkit-config.inc: Fix apache 2.0 linking with GPL license issue.

- meta-refkit-core/lib/supportedrecipes.py
With sources reporting enabled, check_build() fails to
find pn data for virtual target recipes (e.g., IMAGE_MODE
variant recipes).
Fix the failure by adding a check for 'virtual:' prefixed
fn's too. strip_multiconfig_prefix() becomes roughly equivalent
to bitbake's virtualfn2realfn().
> supportedrecipes.py: fix reporting for virtual recipes

- docker/publish-project.sh
- docker/tester-exec.sh
1st commit:
Recent addition about exposing traceback in main log
created problem where egrep was tried on missing file
in qemu tester case. Shell AND-ed operators are not
performed by left-to-right logic, commands are attempted first.
2nd commit avoids publisher error in case of missing sdk/*.sh
which can happen in certain build failure case.
> CI : Fix attempt to egrep missing file, avoid publisher error on missing sdk/*.sh

- docker/publish-project.sh
It appears with new tar 1.29 on Ubuntu 17.04,
build/ and others end up included in source archive.
Adjust tar options to work with older and newer tar versions.
> CI publish-project.sh: adjust tar options to exclude correctly

- meta-refkit/conf/distro/include/refkit-supported-recipes.txt
- meta-refkit/conf/distro/refkit.conf
libmnl recipe from meta-networking was moved to OE-core while
fixing some Yocto Compliance checker issues.
Modify supported-recipes.txt to adapt to that change.
> refkit: use libmnl from @core layer

- doc/hardware.rst
[skip-ci]
The builds are no longer tested on Intel 570x so drop
its section from doc/hardware.rst.
> hardware.rst: drop Intel 570x

- meta-flatpak/recipes-ostree/ostree/ostree_git.bb
Updated ostree to the latest tagged upstream release v2017.13.
This should fix libglnx compilation problems when compiling
against glib-2.54.2 or newer.
The recently added bash completion has been split out to a
submodule of its own. If you have bash in your image and want
autocompletion for ostree, add the submodule to the image.
Signed-off-by: Krisztian Litkey <krisztian.litkey@intel.com>
> meta-flatpak: fix ostree build failure with updated glib-2.0 (2.54.2).

- meta-refkit/conf/distro/refkit.conf
ovmf UEFI secure boot patch is now provided by upstream meta-intel,
not needed in refkit anymore.
> Remove ovmf secure boot patch
